name: 'Configuration Overview'
type: module
description: 'Display an overview of configuration states.'
core_version_requirement: ^9 || ^10
package: 'Administration'
dependencies:
  - config_override_warn:config_override_warn

# Information added by Drupal.org packaging script on 2023-09-04
version: '2.1.1'
project: 'config_overview'
datestamp: 1693813801
