name: Config Override Warn
description: Provide a warning message on configuration forms when any values on the form are possibly being overridden.
type: module
core_version_requirement: ^9 || ^10

# Information added by Drupal.org packaging script on 2023-04-07
version: '8.x-1.4'
project: 'config_override_warn'
datestamp: 1680829140
